# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - name: setup apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang-format
        
    - name: run clang-format
      run: |
        cd $HOME
        git clone --recursive https://github.com/scgmlz/BornAgain.git
        cd BornAgain
        git checkout develop
        clang-format --version
